export interface IRegistrationDto {
  "Name": "string",
  "FatherName": "string",
  "Mothername": "string",
  "BSSYear": "string",
  "DOB" : "2023-01-11T15:05:25.041Z",
  "UniversityBatch": "string",
  "MSSYear": "string",
  "Email": "string",
  "Mobile": "string",
  "WhatsAppp": "string",
  "FacebookId": "string",
  "BloodGroup": "string",
  "Designation": "string",
  "Profession": "string",
  "OfficeAddress": "string",
  "PresentAddress": "string",
  "PermanentAddress": "string",
  "SpouseName": "string",
  "NumberOfKids": 0,
  "MarriageAnniversary": "string",
  "Interest": "string",
  "Achievements": "string",
  "ProfilePicture": "string",
  "Id": 0,
  "IsActive": true,
  "CreateDate": "2023-01-11T15:05:25.041Z",
  "UpdatedDate": "2023-01-11T15:05:25.041Z",
  "CreatedBy": 0,
  "UpdatedBy": 0
}
